# Define the system of units to use internally.
InternalUnitSystem:
  UnitMass_in_cgs:     1.988e+43 # 10^10 Solar masses
  UnitLength_in_cgs:   3.086e+21 # kpc
  UnitVelocity_in_cgs: 1e5       # km / s
  UnitCurrent_in_cgs:  1         # Amperes
  UnitTemp_in_cgs:     1         # Kelvin

Scheduler:
  max_top_level_cells: 16
  cell_sub_size_self_grav:   2048
  cell_subdepth_diff_grav:   2
  cell_split_size:           200
  cell_extra_gparts:         100         # (Optional) Number of spare gparts per top-level allocated at rebuild time for on-the-fly creation.
  cell_extra_sparts:         100
  
# Parameters governing the time integration (Set dt_min and dt_max to the same value for a fixed time-step run.)
TimeIntegration:
  time_begin:          0.      # The starting time of the simulation (in internal units).
  time_end:            2.0     # The end time of the simulation (in internal units).
  dt_min:              1e-11    # The minimal time-step size of the simulation (in internal units).
  dt_max:              1e-4    # The maximal time-step size of the simulation (in internal units).

# Parameters for the self-gravity scheme
Gravity:
  eta:                    0.002    # Constant dimensionless multiplier for time integration.
  theta:                  0.6     # Opening angle (Multipole acceptance criterion)
  MAC:                           geometric  # Choice of mulitpole acceptance criterion: 'adaptive' OR 'geometric'.
  epsilon_fmm:                   0.001     # Tolerance parameter for the adaptive multipole acceptance criterion.
  theta_cr:                      0.7       # Opening angle for the purely gemoetric criterion.
  comoving_DM_softening:     1.0e-3 # Comoving softening length (in internal units).
  max_physical_DM_softening: 1.0e-3    # Physical softening length (in internal units).
  comoving_baryon_softening:     0.07429 # Comoving softening length (in internal units).
  max_physical_baryon_softening: 0.01485    # Physical softening length (in internal units).
  softening_ratio_background:    0.0285714      # Fraction of the mean inter-particle separation to use as Plummer-equivalent softening for the background DM particles.
  mesh_side_length:       128        # Number of cells along each axis for the periodic gravity mesh.
  
# Parameters governing the snapshots
Snapshots:
  basename:            snap/output  # Common part of the name of output files
  time_first:          0.      # Time of the first output (in internal units)
  delta_time:          2e-1    # Time difference between consecutive outputs (in internal units)

# Parameters governing the conserved quantities statistics
Statistics:
  delta_time:          1e-3    # Time between statistics output

# Parameters related to the initial conditions
InitialConditions:
  file_name:          plummer.hdf5 # The file to read
  shift: [2.,2.,2.]
  periodic:           0
